### ISSUE TITLE
Software Components View does not like parenthesis in Csub tag

### ISSUE THREAD

**Issue by gauthiergodart** [ARM-software/vscode-cmsis-csolution#51] opened 2024-02-08 09:58 UTC
Type: Bug Report

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.86.0
- Extension Version: 1.12.7

When a component is defined into the PDSC with parenthesis in a Csub tag (e.g. Csub="Test (parenthesis)"), a bug occurs when one try to select the corresponding component via the Software Components view in VS Code: the component appears selected for a few seconds, but then, it is automatically unchecked. The dependencies of the component are not signaled to the user, and the user gets the feeling the component could not be selected. But, in the cproject.yml file, the component is actually referenced.
In other words, there is a bug in the parser used in background, which fails to handle parenthesis into Csub tags from a pdsc file. This bug also reveals wrong error handling: the user is not informed of the issue, and the project remains in a kind of undefined state, with the component being actually added to the environment, without having its dependencies met, and without the user being aware of it.

**To Reproduce**
1. Create a test component into any PDSC. Add a Csub tag, with the value containing a parenthesis
2. Create a project with the corresponding pack
3. Try to select the test component with the Software Components view
4. See that the component gets unselected, whilst being actually added to the cproject.yml file

**Expected behavior**

The component should be actually selectable, and its dependencies should be checked

**Comment by jkrech** [comment] 2024-02-09 12:35
Thanks a lot for reporting your problem with using parenthesis in the "Csub" string. 
While reproducing your scenario the schema check for the <component> element in the pdsc file already triggers an error for me. Parentheses are not allowed in "Csub".
When entering the componentID in a cproject.yml file, the YAML schema check also complaints about the parentheses.
I believe this is the root cause for the problem you are seeing.
The IDE tries to add the componentID to the cproject.yml file but it gets refused as invalid.

**Comment by gauthiergodart** [comment] 2024-02-09 12:59
Thanks for your answer. 
It is kind of weird, because the PDSC schema check never complained with this on our side. What is the version of the schema you have been using?

**Comment by jkrech** [comment] 2024-02-09 14:16
Sorry, my fault. I have used "(" as the first character in `Csub="(custom)"` which is not allowed.
I checked that the CMSIS-Toolbox deals with parenthesis in `Csub` correctly. 
The Software Components View needs to be looked at.

**Comment by mcgordonite** [comment] 2024-02-12 12:03
Hi @gauthiergodart, thanks for reporting this. We've found the issue in the Software Components view and a fix will come in the next release.

**Comment by gauthiergodart** [comment] 2024-02-12 12:51
Hi @mcgordonite, thanks a lot for the update. Feel free to get back to me if I can be of further assistance.

**Comment by mcgordonite** [comment] 2024-02-12 15:58
The fix was just released in version 1.25.0 of the extension.

**Closed by mcgordonite** 2024-02-12 15:58 UTC
Labels: bug
